import XCTest
@testable import AdventOfCode

final class Day23Tests: XCTestCase {
    let smallInput = """
    .....
    ..##.
    ..#..
    .....
    ..##.
    .....
    """

    let input = """
        ..............
        ..............
        .......#......
        .....###.#....
        ...#...#.#....
        ....#...##....
        ...#.###......
        ...##.#.##....
        ....#..#......
        ..............
        ..............
        ..............
        """
    func testDay23_1_small() throws {
        let day = Day23(rawInput: smallInput)
        XCTAssertEqual(day.part1(), 25)
    }

    func testDay23_1() throws {
        let day = Day23(rawInput: input)
        XCTAssertEqual(day.part1(), 110)
    }

    func testDay23_2() throws {
        let day = Day23(rawInput: input)
        XCTAssertEqual(day.part2(), 20)
    }
}
